import 'dart:async';
import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import '../../models/models.dart';
import '../../services/api_service.dart';
import '../../theme/studio_theme.dart';

class SystemTab extends StatefulWidget {
  final ApiService apiService;

  const SystemTab({super.key, required this.apiService});

  @override
  State<SystemTab> createState() => _SystemTabState();
}

class BotConfigItem {
  int botNum;
  String name;
  String role;
  bool enabled;
  String token;
  String room;

  BotConfigItem({
    required this.botNum,
    required this.name,
    required this.role,
    this.enabled = true,
    this.token = '',
    this.room = '',
  });
}

class RoomConfigItem {
  String id;
  String name;
  bool enabled;
  List<int> activeBots;

  RoomConfigItem({
    required this.id,
    required this.name,
    this.enabled = true,
    required this.activeBots,
  });
}

class _SystemTabState extends State<SystemTab> with SingleTickerProviderStateMixin {
  late TabController _subTabController;
  
  // Logs State
  List<LogEntry> _logs = [];
  String _selectedLevel = 'ALL';
  String _logSearchQuery = '';
  bool _autoScrollLogs = true;
  bool _isLoadingLogs = true;
  Timer? _logTimer;
  final ScrollController _logScrollController = ScrollController();
  final TextEditingController _searchController = TextEditingController();

  // Config State
  bool _isVisualEditor = true; // Visual Form vs Raw YAML
  bool _isLoadingConfig = false;
  bool _isSavingConfig = false;
  String _originalRawYaml = '';
  final TextEditingController _rawYamlController = TextEditingController();

  // Structured Config Fields
  int _serverPort = 8000;
  String _adminPassword = '';
  bool _obscureAdminPassword = true;
  bool _enablePolice = true;
  bool _enableWordChain = true;
  bool _enableChaty = true;
  String _radioStreamUrl = '';

  List<BotConfigItem> _botConfigs = [];
  List<RoomConfigItem> _roomConfigs = [];

  @override
  void initState() {
    super.initState();
    _subTabController = TabController(length: 2, vsync: this);
    _initDefaultConfigData();
    _fetchLogs();
    _logTimer = Timer.periodic(const Duration(seconds: 4), (_) => _fetchLogs(silent: true));
    _loadConfig();
  }

  @override
  void dispose() {
    _logTimer?.cancel();
    _subTabController.dispose();
    _logScrollController.dispose();
    _searchController.dispose();
    _rawYamlController.dispose();
    super.dispose();
  }

  void _initDefaultConfigData() {
    _botConfigs = [
      BotConfigItem(botNum: 1, name: 'HR-Greeter', role: 'Welcome & Tips', enabled: true, room: 'VIP Lounge'),
      BotConfigItem(botNum: 2, name: 'HR-Guardian', role: 'Automod & Anti-Raid', enabled: true, room: 'VIP Lounge'),
      BotConfigItem(botNum: 3, name: 'HR-Jukebox', role: 'Voice Radio DJ', enabled: true, room: 'VIP Lounge'),
      BotConfigItem(botNum: 4, name: 'HR-GameHost', role: 'Police & Word Chain', enabled: true, room: 'VIP Lounge'),
      BotConfigItem(botNum: 5, name: 'HR-Chaty', role: '1-on-1 Blind Matchmaker', enabled: true, room: 'VIP Lounge'),
      BotConfigItem(botNum: 6, name: 'HR-Inspector', role: 'Outfit & Emotes Sync', enabled: true, room: 'VIP Lounge'),
    ];

    _roomConfigs = [
      RoomConfigItem(id: '64239850162', name: 'VIP Lounge', enabled: true, activeBots: [1, 2, 3, 4, 5, 6]),
      RoomConfigItem(id: '64239850199', name: 'Chill Rooftop', enabled: false, activeBots: [1, 3]),
    ];
  }

  // Parses raw YAML into structured fields
  void _parseYamlToFields(String yaml) {
    _originalRawYaml = yaml;
    _rawYamlController.text = yaml;

    // Port
    final portMatch = RegExp(r'port:\s*(\d+)').firstMatch(yaml);
    if (portMatch != null) {
      _serverPort = int.tryParse(portMatch.group(1) ?? '8000') ?? 8000;
    }

    // Admin password
    final pwdMatch = RegExp(r'admin_password:\s*["'']?([^"''\n\r]+)["'']?').firstMatch(yaml);
    if (pwdMatch != null) {
      _adminPassword = pwdMatch.group(1)?.trim() ?? '';
    }

    // Stream URL
    final streamMatch = RegExp(r'radio_stream_url:\s*["'']?([^"''\n\r]+)["'']?').firstMatch(yaml);
    if (streamMatch != null) {
      _radioStreamUrl = streamMatch.group(1)?.trim() ?? '';
    }

    // Mini-games toggles
    if (yaml.contains('police_and_thief: false')) _enablePolice = false;
    if (yaml.contains('word_chain: false')) _enableWordChain = false;
    if (yaml.contains('chaty_matchmaker: false')) _enableChaty = false;
  }

  // Generates clean formatted YAML from visual fields
  String _generateYamlFromFields() {
    final buffer = StringBuffer();
    buffer.writeln('# ================================================');
    buffer.writeln('# Highrise Studio Ecosystem Configuration');
    buffer.writeln('# Auto-generated by Highrise Studio Android App');
    buffer.writeln('# ================================================\n');

    buffer.writeln('server:');
    buffer.writeln('  port: $_serverPort');
    buffer.writeln('  admin_password: "$_adminPassword"');
    buffer.writeln('');

    buffer.writeln('bots:');
    for (var b in _botConfigs) {
      buffer.writeln('  - bot_num: ${b.botNum}');
      buffer.writeln('    name: "${b.name}"');
      buffer.writeln('    role: "${b.role}"');
      buffer.writeln('    enabled: ${b.enabled}');
      buffer.writeln('    room: "${b.room}"');
      if (b.token.isNotEmpty) {
        buffer.writeln('    token: "${b.token}"');
      }
    }
    buffer.writeln('');

    buffer.writeln('rooms:');
    for (var r in _roomConfigs) {
      buffer.writeln('  - id: "${r.id}"');
      buffer.writeln('    name: "${r.name}"');
      buffer.writeln('    enabled: ${r.enabled}');
      buffer.writeln('    active_bots: [${r.activeBots.join(', ')}]');
    }
    buffer.writeln('');

    buffer.writeln('features:');
    buffer.writeln('  police_and_thief: $_enablePolice');
    buffer.writeln('  word_chain: $_enableWordChain');
    buffer.writeln('  chaty_matchmaker: $_enableChaty');
    buffer.writeln('  radio_stream_url: "$_radioStreamUrl"');

    return buffer.toString();
  }

  Future<void> _fetchLogs({bool silent = false}) async {
    if (!silent) setState(() => _isLoadingLogs = true);
    try {
      final entries = await widget.apiService.getLogs(
        level: _selectedLevel == 'ALL' ? null : _selectedLevel,
      );
      if (mounted) {
        setState(() {
          _logs = entries;
          _isLoadingLogs = false;
        });
        if (_autoScrollLogs && _logScrollController.hasClients) {
          _logScrollController.jumpTo(_logScrollController.position.maxScrollExtent);
        }
      }
    } catch (_) {
      if (mounted && !silent) setState(() => _isLoadingLogs = false);
    }
  }

  Future<void> _loadConfig() async {
    setState(() => _isLoadingConfig = true);
    try {
      final cfg = await widget.apiService.getRawConfig();
      if (mounted) {
        setState(() {
          _parseYamlToFields(cfg);
          _isLoadingConfig = false;
        });
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isLoadingConfig = false);
      }
    }
  }

  Future<void> _saveConfig() async {
    setState(() => _isSavingConfig = true);
    final contentToSave = _isVisualEditor ? _generateYamlFromFields() : _rawYamlController.text;
    try {
      final ok = await widget.apiService.saveRawConfig(contentToSave);
      if (mounted) {
        setState(() {
          _isSavingConfig = false;
          _originalRawYaml = contentToSave;
          _rawYamlController.text = contentToSave;
        });
        if (ok) {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Configuration saved and applied to server!'),
              backgroundColor: StudioTheme.accentEmerald,
            ),
          );
        } else {
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(
              content: Text('Server rejected configuration update'),
              backgroundColor: StudioTheme.accentRed,
            ),
          );
        }
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isSavingConfig = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Error saving config: $e'),
            backgroundColor: StudioTheme.accentRed,
          ),
        );
      }
    }
  }

  void _confirmRestart({required bool hard}) {
    showDialog(
      context: context,
      builder: (ctx) => AlertDialog(
        backgroundColor: StudioTheme.surfaceDark,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        title: Row(
          children: [
            Icon(Icons.warning_amber_rounded, color: hard ? StudioTheme.accentRed : StudioTheme.accentYellow),
            const SizedBox(width: 8),
            Text(hard ? 'Hard Restart Server?' : 'Soft Restart Bots?', style: const TextStyle(color: Colors.white)),
          ],
        ),
        content: Text(
          hard
              ? 'This will reboot the entire Wispbyte container process. All active bot rooms and games will momentarily disconnect.'
              : 'This will re-initialize bot instances and reload configuration without dropping the host container.',
          style: const TextStyle(color: StudioTheme.textMuted, fontSize: 13),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: const Text('Cancel', style: TextStyle(color: StudioTheme.textMuted)),
          ),
          ElevatedButton(
            style: ElevatedButton.styleFrom(
              backgroundColor: hard ? StudioTheme.accentRed : StudioTheme.accentSky,
              foregroundColor: StudioTheme.bgDark,
            ),
            onPressed: () async {
              Navigator.pop(ctx);
              final ok = await widget.apiService.restartSystem(hard: hard);
              if (mounted) {
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(
                    content: Text(ok ? 'Restart signal dispatched' : 'Failed to send restart signal'),
                    backgroundColor: ok ? StudioTheme.accentEmerald : StudioTheme.accentRed,
                  ),
                );
              }
            },
            child: Text(hard ? 'Reboot Container' : 'Restart Bots', style: const TextStyle(fontWeight: FontWeight.bold)),
          ),
        ],
      ),
    );
  }

  void _showAddRoomDialog() {
    final idCtrl = TextEditingController();
    final nameCtrl = TextEditingController();
    final List<int> selectedBots = [1, 2, 3, 4, 5, 6];

    showDialog(
      context: context,
      builder: (ctx) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          backgroundColor: StudioTheme.surfaceDark,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
          title: const Row(
            children: [
              Icon(Icons.add_business_rounded, color: StudioTheme.accentSky),
              SizedBox(width: 8),
              Text('Configure New Room', style: TextStyle(color: Colors.white, fontSize: 16)),
            ],
          ),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextField(
                controller: nameCtrl,
                style: const TextStyle(color: Colors.white, fontSize: 13),
                decoration: InputDecoration(
                  labelText: 'Room Name',
                  hintText: 'e.g. Chill Rooftop',
                  filled: true,
                  fillColor: StudioTheme.cardDark,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                ),
              ),
              const SizedBox(height: 10),
              TextField(
                controller: idCtrl,
                style: const TextStyle(color: Colors.white, fontSize: 13),
                decoration: InputDecoration(
                  labelText: 'Highrise Room ID',
                  hintText: 'e.g. 64239850199',
                  filled: true,
                  fillColor: StudioTheme.cardDark,
                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                ),
              ),
              const SizedBox(height: 14),
              const Text('Active Bots to Deploy:', style: TextStyle(color: StudioTheme.textMuted, fontSize: 12)),
              const SizedBox(height: 6),
              Wrap(
                spacing: 6,
                children: List.generate(6, (i) {
                  final bNum = i + 1;
                  final isSelected = selectedBots.contains(bNum);
                  return FilterChip(
                    label: Text('Bot $bNum', style: TextStyle(fontSize: 11, color: isSelected ? Colors.black : Colors.white)),
                    selected: isSelected,
                    selectedColor: StudioTheme.accentSky,
                    backgroundColor: StudioTheme.cardDark,
                    onSelected: (val) {
                      setDialogState(() {
                        if (val) {
                          selectedBots.add(bNum);
                        } else {
                          selectedBots.remove(bNum);
                        }
                      });
                    },
                  );
                }),
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(ctx),
              child: const Text('Cancel', style: TextStyle(color: StudioTheme.textMuted)),
            ),
            ElevatedButton(
              style: ElevatedButton.styleFrom(
                backgroundColor: StudioTheme.accentSky,
                foregroundColor: StudioTheme.bgDark,
              ),
              onPressed: () {
                final id = idCtrl.text.trim();
                final name = nameCtrl.text.trim().isEmpty ? 'Custom Room' : nameCtrl.text.trim();
                if (id.isNotEmpty) {
                  setState(() {
                    _roomConfigs.add(RoomConfigItem(
                      id: id,
                      name: name,
                      enabled: true,
                      activeBots: List.from(selectedBots),
                    ));
                  });
                  Navigator.pop(ctx);
                }
              },
              child: const Text('Add Room', style: TextStyle(fontWeight: FontWeight.bold)),
            ),
          ],
        ),
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        // Sub Header Tab Bar
        Container(
          color: StudioTheme.cardDark,
          child: TabBar(
            controller: _subTabController,
            indicatorColor: StudioTheme.accentSky,
            labelColor: StudioTheme.accentSky,
            unselectedLabelColor: StudioTheme.textMuted,
            indicatorSize: TabBarIndicatorSize.tab,
            tabs: const [
              Tab(icon: Icon(Icons.terminal_rounded, size: 18), text: 'Live Console'),
              Tab(icon: Icon(Icons.tune_rounded, size: 18), text: 'Config & Fleet Settings'),
            ],
          ),
        ),

        // Tab Content
        Expanded(
          child: TabBarView(
            controller: _subTabController,
            children: [
              _buildConsoleView(),
              _buildModernConfigView(),
            ],
          ),
        ),
      ],
    );
  }

  // --- TAB 1: Console View ---
  Widget _buildConsoleView() {
    final filteredLogs = _logs.where((l) {
      if (_logSearchQuery.isEmpty) return true;
      return l.message.toLowerCase().contains(_logSearchQuery.toLowerCase()) ||
          l.logger.toLowerCase().contains(_logSearchQuery.toLowerCase());
    }).toList();

    return Column(
      children: [
        // Filter and Search Toolbar
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
          color: StudioTheme.surfaceDark,
          child: Column(
            children: [
              Row(
                children: [
                  Expanded(
                    child: SingleChildScrollView(
                      scrollDirection: Axis.horizontal,
                      child: Row(
                        children: ['ALL', 'INFO', 'WARN', 'ERROR', 'DEBUG'].map((lvl) {
                          final isSelected = _selectedLevel == lvl;
                          return Padding(
                            padding: const EdgeInsets.only(right: 6),
                            child: FilterChip(
                              label: Text(lvl, style: TextStyle(fontSize: 11, color: isSelected ? Colors.black : Colors.white)),
                              selected: isSelected,
                              selectedColor: StudioTheme.accentSky,
                              backgroundColor: StudioTheme.cardDark,
                              showCheckmark: false,
                              padding: const EdgeInsets.symmetric(horizontal: 6),
                              onSelected: (_) {
                                setState(() => _selectedLevel = lvl);
                                _fetchLogs();
                              },
                            ),
                          );
                        }).toList(),
                      ),
                    ),
                  ),
                  IconButton(
                    icon: Icon(
                      _autoScrollLogs ? Icons.vertical_align_bottom : Icons.pause_circle_outline,
                      color: _autoScrollLogs ? StudioTheme.accentSky : StudioTheme.textMuted,
                      size: 20,
                    ),
                    onPressed: () => setState(() => _autoScrollLogs = !_autoScrollLogs),
                    tooltip: 'Auto-scroll to latest',
                  ),
                  IconButton(
                    icon: const Icon(Icons.refresh, color: StudioTheme.textMuted, size: 20),
                    onPressed: () => _fetchLogs(),
                    tooltip: 'Refresh logs',
                  ),
                ],
              ),
              const SizedBox(height: 6),
              SizedBox(
                height: 36,
                child: TextField(
                  controller: _searchController,
                  onChanged: (val) => setState(() => _logSearchQuery = val),
                  style: const TextStyle(color: Colors.white, fontSize: 13),
                  decoration: InputDecoration(
                    hintText: 'Filter log messages...',
                    hintStyle: const TextStyle(color: StudioTheme.textMuted, fontSize: 12),
                    prefixIcon: const Icon(Icons.search, color: StudioTheme.textMuted, size: 16),
                    suffixIcon: _logSearchQuery.isNotEmpty
                        ? IconButton(
                            icon: const Icon(Icons.clear, color: StudioTheme.textMuted, size: 16),
                            onPressed: () {
                              _searchController.clear();
                              setState(() => _logSearchQuery = '');
                            },
                          )
                        : null,
                    filled: true,
                    fillColor: StudioTheme.cardDark,
                    contentPadding: const EdgeInsets.symmetric(vertical: 4),
                    border: OutlineInputBorder(
                      borderRadius: BorderRadius.circular(8),
                      borderSide: BorderSide.none,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),

        // Supervisor Restart Bar
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          decoration: BoxDecoration(
            color: StudioTheme.bgDark,
            border: Border(bottom: BorderSide(color: StudioTheme.borderDark)),
          ),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Row(
                children: [
                  Icon(Icons.power_settings_new, color: StudioTheme.accentSky, size: 16),
                  SizedBox(width: 6),
                  Text('Supervisor Power:', style: TextStyle(color: StudioTheme.textMuted, fontSize: 12)),
                ],
              ),
              Row(
                children: [
                  ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: StudioTheme.surfaceDark,
                      foregroundColor: StudioTheme.accentSky,
                      side: const BorderSide(color: StudioTheme.accentSky, width: 1),
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                      minimumSize: Size.zero,
                      tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    onPressed: () => _confirmRestart(hard: false),
                    child: const Text('Soft Restart', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                  ),
                  const SizedBox(width: 8),
                  ElevatedButton(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: StudioTheme.accentRed.withOpacity(0.15),
                      foregroundColor: StudioTheme.accentRed,
                      side: const BorderSide(color: StudioTheme.accentRed, width: 1),
                      padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                      minimumSize: Size.zero,
                      tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                    onPressed: () => _confirmRestart(hard: true),
                    child: const Text('Reboot Server', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold)),
                  ),
                ],
              ),
            ],
          ),
        ),

        // Logs Output Console
        Expanded(
          child: _isLoadingLogs
              ? const Center(child: CircularProgressIndicator(color: StudioTheme.accentSky))
              : filteredLogs.isEmpty
                  ? const Center(
                      child: Text('No log entries match filter', style: TextStyle(color: StudioTheme.textMuted)),
                    )
                  : Container(
                      color: const Color(0xFF070A11),
                      child: ListView.builder(
                        controller: _logScrollController,
                        padding: const EdgeInsets.all(12),
                        itemCount: filteredLogs.length,
                        itemBuilder: (context, index) {
                          final log = filteredLogs[index];
                          final timeStr = DateFormat('HH:mm:ss').format(log.timestamp);
                          Color levelColor = StudioTheme.accentSky;
                          if (log.level == 'ERROR') levelColor = StudioTheme.accentRed;
                          if (log.level == 'WARN') levelColor = StudioTheme.accentYellow;
                          if (log.level == 'DEBUG') levelColor = StudioTheme.textMuted;

                          return Padding(
                            padding: const EdgeInsets.symmetric(vertical: 2),
                            child: Row(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                Text(
                                  '[$timeStr] ',
                                  style: const TextStyle(
                                    fontFamily: 'monospace',
                                    color: StudioTheme.textMuted,
                                    fontSize: 11,
                                  ),
                                ),
                                Container(
                                  width: 48,
                                  alignment: Alignment.centerLeft,
                                  child: Text(
                                    log.level,
                                    style: TextStyle(
                                      fontFamily: 'monospace',
                                      color: levelColor,
                                      fontWeight: FontWeight.bold,
                                      fontSize: 11,
                                    ),
                                  ),
                                ),
                                Expanded(
                                  child: Text(
                                    log.message,
                                    style: const TextStyle(
                                      fontFamily: 'monospace',
                                      color: Colors.white,
                                      fontSize: 11,
                                    ),
                                  ),
                                ),
                              ],
                            ),
                          );
                        },
                      ),
                    ),
        ),
      ],
    );
  }

  // --- TAB 2: MODERN INTERACTIVE CONFIG VIEW ---
  Widget _buildModernConfigView() {
    if (_isLoadingConfig) {
      return const Center(child: CircularProgressIndicator(color: StudioTheme.accentSky));
    }

    return Column(
      children: [
        // Mode Switcher Bar (Visual Form vs Raw YAML) & Save Button
        Container(
          padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
          color: StudioTheme.surfaceDark,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              // Segmented Switcher
              Container(
                decoration: BoxDecoration(
                  color: StudioTheme.cardDark,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: StudioTheme.borderDark),
                ),
                child: Row(
                  children: [
                    InkWell(
                      onTap: () {
                        if (!_isVisualEditor) {
                          _parseYamlToFields(_rawYamlController.text);
                          setState(() => _isVisualEditor = true);
                        }
                      },
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                        decoration: BoxDecoration(
                          color: _isVisualEditor ? StudioTheme.accentSky : Colors.transparent,
                          borderRadius: BorderRadius.circular(7),
                        ),
                        child: Row(
                          children: [
                            Icon(Icons.widgets_outlined, size: 14, color: _isVisualEditor ? StudioTheme.bgDark : StudioTheme.textMuted),
                            const SizedBox(width: 4),
                            Text('Visual Form', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: _isVisualEditor ? StudioTheme.bgDark : StudioTheme.textMuted)),
                          ],
                        ),
                      ),
                    ),
                    InkWell(
                      onTap: () {
                        if (_isVisualEditor) {
                          _rawYamlController.text = _generateYamlFromFields();
                          setState(() => _isVisualEditor = false);
                        }
                      },
                      child: Container(
                        padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6),
                        decoration: BoxDecoration(
                          color: !_isVisualEditor ? StudioTheme.accentSky : Colors.transparent,
                          borderRadius: BorderRadius.circular(7),
                        ),
                        child: Row(
                          children: [
                            Icon(Icons.code_rounded, size: 14, color: !_isVisualEditor ? StudioTheme.bgDark : StudioTheme.textMuted),
                            const SizedBox(width: 4),
                            Text('Raw YAML', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: !_isVisualEditor ? StudioTheme.bgDark : StudioTheme.textMuted)),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              // Action Buttons
              Row(
                children: [
                  IconButton(
                    icon: const Icon(Icons.refresh, color: StudioTheme.textMuted, size: 20),
                    onPressed: _loadConfig,
                    tooltip: 'Reload from server',
                  ),
                  ElevatedButton.icon(
                    style: ElevatedButton.styleFrom(
                      backgroundColor: StudioTheme.accentEmerald,
                      foregroundColor: StudioTheme.bgDark,
                      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                      minimumSize: Size.zero,
                      tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                    ),
                    onPressed: _isSavingConfig ? null : _saveConfig,
                    icon: _isSavingConfig
                        ? const SizedBox(
                            width: 12,
                            height: 12,
                            child: CircularProgressIndicator(color: StudioTheme.bgDark, strokeWidth: 2),
                          )
                        : const Icon(Icons.save, size: 14),
                    label: const Text('Save & Apply', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 12)),
                  ),
                ],
              ),
            ],
          ),
        ),

        // Body Content
        Expanded(
          child: _isVisualEditor ? _buildVisualFieldsForm() : _buildRawYamlEditor(),
        ),
      ],
    );
  }

  // Visual Interactive Form
  Widget _buildVisualFieldsForm() {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // 1. Server Security & Port Card
          _buildSectionHeader('Server Credentials & Port', Icons.security),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(16),
            decoration: BoxDecoration(
              color: StudioTheme.cardDark,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: StudioTheme.borderDark),
            ),
            child: Column(
              children: [
                Row(
                  children: [
                    Expanded(
                      flex: 1,
                      child: TextField(
                        keyboardType: TextInputType.number,
                        style: const TextStyle(color: Colors.white, fontSize: 13),
                        decoration: InputDecoration(
                          labelText: 'HTTP Port',
                          labelStyle: const TextStyle(color: StudioTheme.textMuted, fontSize: 12),
                          filled: true,
                          fillColor: StudioTheme.surfaceDark,
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                        ),
                        controller: TextEditingController(text: _serverPort.toString()),
                        onChanged: (val) => _serverPort = int.tryParse(val) ?? 8000,
                      ),
                    ),
                    const SizedBox(width: 12),
                    Expanded(
                      flex: 2,
                      child: TextField(
                        obscureText: _obscureAdminPassword,
                        style: const TextStyle(color: Colors.white, fontSize: 13),
                        decoration: InputDecoration(
                          labelText: 'Admin Password',
                          labelStyle: const TextStyle(color: StudioTheme.textMuted, fontSize: 12),
                          filled: true,
                          fillColor: StudioTheme.surfaceDark,
                          border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                          suffixIcon: IconButton(
                            icon: Icon(
                              _obscureAdminPassword ? Icons.visibility_off : Icons.visibility,
                              color: StudioTheme.textMuted,
                              size: 18,
                            ),
                            onPressed: () => setState(() => _obscureAdminPassword = !_obscureAdminPassword),
                          ),
                        ),
                        controller: TextEditingController(text: _adminPassword),
                        onChanged: (val) => _adminPassword = val,
                      ),
                    ),
                  ],
                ),
              ],
            ),
          ),

          const SizedBox(height: 20),

          // 2. Bot Fleet Configuration
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              _buildSectionHeader('Bot Fleet (${_botConfigs.where((b) => b.enabled).length}/${_botConfigs.length} Enabled)', Icons.smart_toy_outlined),
            ],
          ),
          const SizedBox(height: 8),

          ListView.separated(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: _botConfigs.length,
            separatorBuilder: (_, __) => const SizedBox(height: 8),
            itemBuilder: (context, index) {
              final bot = _botConfigs[index];
              Color botColor = StudioTheme.accentSky;
              if (bot.botNum == 2) botColor = StudioTheme.accentPink;
              if (bot.botNum == 3) botColor = StudioTheme.accentYellow;
              if (bot.botNum == 4) botColor = StudioTheme.accentEmerald;
              if (bot.botNum == 5) botColor = StudioTheme.accentPurple;
              if (bot.botNum == 6) botColor = Colors.cyan;

              return Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: StudioTheme.cardDark,
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(
                    color: bot.enabled ? botColor.withOpacity(0.4) : StudioTheme.borderDark,
                  ),
                ),
                child: Column(
                  children: [
                    Row(
                      children: [
                        CircleAvatar(
                          radius: 14,
                          backgroundColor: botColor.withOpacity(0.2),
                          child: Text(
                            'B${bot.botNum}',
                            style: TextStyle(color: botColor, fontSize: 11, fontWeight: FontWeight.bold),
                          ),
                        ),
                        const SizedBox(width: 10),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(bot.name, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 13)),
                              Text(bot.role, style: const TextStyle(color: StudioTheme.textMuted, fontSize: 11)),
                            ],
                          ),
                        ),
                        Switch(
                          value: bot.enabled,
                          activeColor: botColor,
                          activeTrackColor: botColor.withOpacity(0.4),
                          inactiveTrackColor: StudioTheme.surfaceDark,
                          onChanged: (val) {
                            setState(() => bot.enabled = val);
                          },
                        ),
                      ],
                    ),
                    if (bot.enabled) ...[
                      const SizedBox(height: 8),
                      Row(
                        children: [
                          Expanded(
                            child: SizedBox(
                              height: 36,
                              child: TextField(
                                controller: TextEditingController(text: bot.room),
                                onChanged: (val) => bot.room = val,
                                style: const TextStyle(color: Colors.white, fontSize: 12),
                                decoration: InputDecoration(
                                  labelText: 'Assigned Room',
                                  labelStyle: const TextStyle(color: StudioTheme.textMuted, fontSize: 11),
                                  filled: true,
                                  fillColor: StudioTheme.surfaceDark,
                                  contentPadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 4),
                                  border: OutlineInputBorder(borderRadius: BorderRadius.circular(8)),
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ],
                ),
              );
            },
          ),

          const SizedBox(height: 20),

          // 3. Multi-Rooms Configuration
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              _buildSectionHeader('Multi-Room Ecosystem (${_roomConfigs.length} Rooms)', Icons.meeting_room_outlined),
              TextButton.icon(
                onPressed: _showAddRoomDialog,
                icon: const Icon(Icons.add, size: 16, color: StudioTheme.accentSky),
                label: const Text('Add Room', style: TextStyle(color: StudioTheme.accentSky, fontSize: 12, fontWeight: FontWeight.bold)),
              ),
            ],
          ),
          const SizedBox(height: 8),

          ListView.separated(
            shrinkWrap: true,
            physics: const NeverScrollableScrollPhysics(),
            itemCount: _roomConfigs.length,
            separatorBuilder: (_, __) => const SizedBox(height: 8),
            itemBuilder: (context, index) {
              final room = _roomConfigs[index];
              return Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: StudioTheme.cardDark,
                  borderRadius: BorderRadius.circular(14),
                  border: Border.all(
                    color: room.enabled ? StudioTheme.accentSky.withOpacity(0.3) : StudioTheme.borderDark,
                  ),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        const Icon(Icons.meeting_room, color: StudioTheme.accentSky, size: 18),
                        const SizedBox(width: 8),
                        Expanded(
                          child: Column(
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text(room.name, style: const TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontSize: 13)),
                              Text('ID: ${room.id}', style: const TextStyle(color: StudioTheme.textMuted, fontSize: 11)),
                            ],
                          ),
                        ),
                        Switch(
                          value: room.enabled,
                          activeColor: StudioTheme.accentSky,
                          activeTrackColor: StudioTheme.accentSky.withOpacity(0.4),
                          inactiveTrackColor: StudioTheme.surfaceDark,
                          onChanged: (val) => setState(() => room.enabled = val),
                        ),
                        IconButton(
                          icon: const Icon(Icons.delete_outline, color: StudioTheme.accentRed, size: 18),
                          onPressed: () {
                            setState(() => _roomConfigs.removeAt(index));
                          },
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    // Bot chips for this room
                    Wrap(
                      spacing: 4,
                      children: List.generate(6, (bIdx) {
                        final bNum = bIdx + 1;
                        final isAssigned = room.activeBots.contains(bNum);
                        return FilterChip(
                          label: Text('Bot $bNum', style: TextStyle(fontSize: 10, color: isAssigned ? Colors.black : Colors.white)),
                          selected: isAssigned,
                          selectedColor: StudioTheme.accentSky,
                          backgroundColor: StudioTheme.surfaceDark,
                          padding: const EdgeInsets.symmetric(horizontal: 4),
                          onSelected: (val) {
                            setState(() {
                              if (val) {
                                room.activeBots.add(bNum);
                              } else {
                                room.activeBots.remove(bNum);
                              }
                            });
                          },
                        );
                      }),
                    ),
                  ],
                ),
              );
            },
          ),

          const SizedBox(height: 20),

          // 4. Features, Games & Radio Stream Card
          _buildSectionHeader('Features & Integrations', Icons.sports_esports_outlined),
          const SizedBox(height: 8),
          Container(
            padding: const EdgeInsets.all(14),
            decoration: BoxDecoration(
              color: StudioTheme.cardDark,
              borderRadius: BorderRadius.circular(16),
              border: Border.all(color: StudioTheme.borderDark),
            ),
            child: Column(
              children: [
                SwitchListTile(
                  contentPadding: EdgeInsets.zero,
                  dense: true,
                  title: const Text('Police & Thief Mini-Game', style: TextStyle(color: Colors.white, fontSize: 13, fontWeight: FontWeight.w600)),
                  subtitle: const Text('Auto-start game logic in room', style: TextStyle(color: StudioTheme.textMuted, fontSize: 11)),
                  value: _enablePolice,
                  activeColor: StudioTheme.accentSky,
                  onChanged: (val) => setState(() => _enablePolice = val),
                ),
                const Divider(color: StudioTheme.borderDark),
                SwitchListTile(
                  contentPadding: EdgeInsets.zero,
                  dense: true,
                  title: const Text('Word Chain (Shiritori)', style: TextStyle(color: Colors.white, fontSize: 13, fontWeight: FontWeight.w600)),
                  subtitle: const Text('Letter vocabulary game in room', style: TextStyle(color: StudioTheme.textMuted, fontSize: 11)),
                  value: _enableWordChain,
                  activeColor: StudioTheme.accentPink,
                  onChanged: (val) => setState(() => _enableWordChain = val),
                ),
                const Divider(color: StudioTheme.borderDark),
                SwitchListTile(
                  contentPadding: EdgeInsets.zero,
                  dense: true,
                  title: const Text('Chaty 1-on-1 Matchmaker', style: TextStyle(color: Colors.white, fontSize: 13, fontWeight: FontWeight.w600)),
                  subtitle: const Text('Anonymous blind dating pairings', style: TextStyle(color: StudioTheme.textMuted, fontSize: 11)),
                  value: _enableChaty,
                  activeColor: StudioTheme.accentPurple,
                  onChanged: (val) => setState(() => _enableChaty = val),
                ),
                const Divider(color: StudioTheme.borderDark),
                const SizedBox(height: 6),
                TextField(
                  controller: TextEditingController(text: _radioStreamUrl),
                  onChanged: (val) => _radioStreamUrl = val,
                  style: const TextStyle(color: Colors.white, fontSize: 12),
                  decoration: InputDecoration(
                    labelText: 'Default Voice Radio Stream URL',
                    hintText: 'http://s1.wispbyte.com:8000/radio.mp3',
                    labelStyle: const TextStyle(color: StudioTheme.textMuted, fontSize: 11),
                    filled: true,
                    fillColor: StudioTheme.surfaceDark,
                    border: OutlineInputBorder(borderRadius: BorderRadius.circular(10)),
                  ),
                ),
              ],
            ),
          ),

          const SizedBox(height: 24),
        ],
      ),
    );
  }

  // Raw YAML Editor
  Widget _buildRawYamlEditor() {
    return Container(
      color: const Color(0xFF080C14),
      padding: const EdgeInsets.all(12),
      child: TextField(
        controller: _rawYamlController,
        maxLines: null,
        expands: true,
        keyboardType: TextInputType.multiline,
        style: const TextStyle(
          fontFamily: 'monospace',
          fontSize: 12,
          color: Color(0xFFE2E8F0),
          height: 1.4,
        ),
        decoration: const InputDecoration(
          border: InputBorder.none,
          hintText: '# YAML Configuration...',
          hintStyle: TextStyle(color: StudioTheme.textMuted),
        ),
      ),
    );
  }

  Widget _buildSectionHeader(String title, IconData icon) {
    return Row(
      children: [
        Icon(icon, color: StudioTheme.accentSky, size: 16),
        const SizedBox(width: 6),
        Text(
          title,
          style: const TextStyle(color: Colors.white, fontSize: 13, fontWeight: FontWeight.bold),
        ),
      ],
    );
  }
}
